### ISSUE TITLE
File number not updating when manually deleting the backups

### ISSUE THREAD

**Issue by iptvcld** [danmed/TasmoBackupV1#10]
File number not updating when manually deleting the backups
- I was testing the backupall.php and made a bunch of backups then manually deleted the backups from the backups folder but the file number on the GUI still says 11.

**Comment by danmed** [comment]
It will update the next time you make a backup.. It only checks at the time of backup.

**Comment by iptvcld** [comment]
So i did a full backup again and the number went to 12 but yet in my folder i just have the 1 backup

**Comment by iptvcld** [comment]
Also i noticed that the Backup Max Count field does not seem to work.  I have it set to 5 and yet i was able to make more than 5 backups; it was not deleting the oldest. Thanks

**Comment by danmed** [comment]
Thanks for the info I'll take a look.

**Comment by danmed** [comment]
So, deleting the backups manually is just going to mess things up.. so the other contributor has pushed some code so that when you delete the device from the gui, it'll delete all the backups too.

Tomorrow i'll work on being able to delete indivudla backups, so that should remove the need to do anything manually.

as for the max backups, that only kick sin on a backup all, not individual backups.. we dont want to restrict you doing individual backups as it may be because you're about to make a change.

**Comment by iptvcld** [comment]
Thanks for looking into this! That delete backup option would be awesome.
- As for Max backups; i am using the backupall.php and its still surpassing the max backup count.  I even just pressed on the backup all button and it went past 5 even though my max is set to 5.

**Comment by danmed** [comment]
Ok, I'll take a look at that too.. 

the delete option is now done.. it's building and should be available in a few mins.
Deleting a device gets rid of all the backups (without confirmation at the moment) and on the list backups page, you can delete individual ones.

I'll open another issue for the max backups

**Comment by iptvcld** [comment]
Excellent, thank you!!
