### ISSUE TITLE
Incorrectly reports backup success!

### ISSUE THREAD

**Issue by gck303** [danmed/TasmoBackupV1#72]
When running I get a message that says the backups have gone okay. But when I look at logs, it is anything but. There is a problem with the directory which is not being correctly reported. 

>>>>>>>>>>>>>>>>>>>>

[17-Jul-2022 18:01:52] WARNING: [pool www] child 133 said into stderr: "NOTICE: PHP message: PHP Warning:  file_put_contents(gck_backups//github-tasmota-release-data.json): failed to open stream: No such file or directory in /var/www/html/lib/functions.inc.php on line 783"

192.168.0.177 - - [17/Jul/2022:18:01:52 +0000] "GET /index.php HTTP/1.1" 200 5807 "http://192.168.0.28:8259/settings.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" "-" 1.724 1.724 . -

2022/07/17 18:01:52 [error] 54#54: *55 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(gck_backups//github-tasmota-release-data.json): failed to open stream: No such file or directory in /var/www/html/lib/functions.inc.php on line 783" while reading upstream, client: 192.168.0.177, server: _, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.28:8259", referrer: "http://192.168.0.28:8259/settings.php"

[17-Jul-2022 18:01:55] WARNING: [pool www] child 133 said into stderr: "NOTICE: PHP message: PHP Warning:  file_put_contents(gck_backups//github-tasmota-release-data.json): failed to open stream: No such file or directory in /var/www/html/lib/functions.inc.php on line 783"

**Comment by patrickdk77** [comment]
That is not incorrectly reporting. The warning message has nothing to do with backups.

I would be concerned why it doesn't have write permission to the backup folder you defined in your config settings though.
But nothing you posted says there was ever a failure to backup.

**Comment by gck303** [comment]
This message says the backups were successful, but they are not!

The problem is being caused by weird permissions in the docker when I move the data directory to my smb share. This issue is about the inconsistency between the message in the and the fact the backups were unsuccessful due to a directory error. 

![2022-07-17 19_48_45-TasmoBackup](https://user-images.githubusercontent.com/30334661/179420465-be15fa46-4b3a-4d42-a9e4-0fea04fa2fd2.png)

**Comment by patrickdk77** [comment]
The log messages you posted have NOTHING to do with backups, they are unrelated.

The weird permissions is nothing that I can resolve, that is something you will have to handle between your docker server and your smb share.

I'm not sure what you want me to do here, you are posting a message about the download list of tasmota version json file isn't able to be saved, and are claiming it is why backups are failing, when the two have nothing to do with each other, so saying backups failed if that unneeded download failed to save would be misleading.

Are your backups not actually being saved? But the reason you pointed out is false. I can dig into the code and see if there is any errors not being captured.

But so far, the bug report is, It claims everything is fine, the permissions on my backup folder are screwed up, and I don't know if backups are really working or not.

**Comment by gck303** [comment]
No, the backups were not working. 

I  set an incorrect directory in the config page, and I ran the backup. It came back VERY quickly and told be the backups were successful. But, they were not. 

I was trying to tell you the 'all backups completed successfully' message is incorrect, as it gets presented after pressing the 'backup now' button and no backups not being done. 

I have started again from scratch and will not touch that parameter. I have now been able to take a backup, though stand by the messaging not being correct.

**Comment by patrickdk77** [comment]
This I can understand. But your description of the problem was, backups says success, but logs say they where not.
Since the log messages have nothing to do with backups and is not even in the backups code, they are unrelated, therefore making the statement of the message being successful or not, unknown, cause the reason stated for why it was invalid was incorrect.

Its hard to know what you mean, if you dig deep into incorrect assumptions to the cause of an issue, instead of just stating the problem, it says success, but (backup folder is empty/unable to download backup file/....) as to a related reason why that message is incorrect.

I should probably add a counter for how many backups where attempted. As of currently, if a backup has been run recently, it will not do another backup of that same device, so it wouldn't take another backup if you just keep smashing the backup all button, it will only attempt devices that have not have a recent backup based on the config settings (normaly 1day).

**Comment by patrickdk77** [comment]
Added backup stats when completed.
